FROM python:3.9.0

WORKDIR /home/

RUN echo 'ahwehasd'

RUN git clone https://github.com/ghgh3644/gsgs.git

WORKDIR /home/gsgs/

RUN echo "SECRET_KEY = django-insecure-+96pvi5+q58yq-to)q9e(^iati4!fsij-2a@h$h1w8taq)+s6%" > .env

RUN pip install -r requirements.txt

RUN pip install gunicorn

RUN pip install mysqlclient

EXPOSE 8000

CMD ["bash", "-c", "python manage.py collectstatic --noinput --settings=gis_3ban_gh1.settings.deploy && python manage.py migrate --settings=gis_3ban_gh1.settings.deploy && gunicorn --env DJANGO_SETTINGS_MODULE=gis_3ban_gh1.settings.deploy gis_3ban_gh1.wsgi --bind 0.0.0.0:8000"]
