# Generated by Django 3.2.4 on 2021-07-13 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewMedel',
            new_name='NewModel',
        ),
    ]
